// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/zjutjh/jxh-go/internal/storage/model"
)

func newKnowledgeEntry(db *gorm.DB, opts ...gen.DOOption) knowledgeEntry {
	_knowledgeEntry := knowledgeEntry{}

	_knowledgeEntry.knowledgeEntryDo.UseDB(db, opts...)
	_knowledgeEntry.knowledgeEntryDo.UseModel(&model.KnowledgeEntry{})

	tableName := _knowledgeEntry.knowledgeEntryDo.TableName()
	_knowledgeEntry.ALL = field.NewAsterisk(tableName)
	_knowledgeEntry.ID = field.NewUint64(tableName, "id")
	_knowledgeEntry.SourceKey = field.NewString(tableName, "source_key")
	_knowledgeEntry.Keyword = field.NewString(tableName, "keyword")
	_knowledgeEntry.EntryType = field.NewString(tableName, "entry_type")
	_knowledgeEntry.Path = field.NewString(tableName, "path")
	_knowledgeEntry.AliasesJSON = field.NewString(tableName, "aliases_json")
	_knowledgeEntry.Category = field.NewString(tableName, "category")
	_knowledgeEntry.TagsJSON = field.NewString(tableName, "tags_json")
	_knowledgeEntry.Answer = field.NewString(tableName, "answer")
	_knowledgeEntry.Content = field.NewString(tableName, "content")
	_knowledgeEntry.Enabled = field.NewBool(tableName, "enabled")
	_knowledgeEntry.ExactReply = field.NewBool(tableName, "exact_reply")
	_knowledgeEntry.AiEnabled = field.NewBool(tableName, "ai_enabled")
	_knowledgeEntry.LastImportRunID = field.NewUint64(tableName, "last_import_run_id")
	_knowledgeEntry.SourceUpdatedAt = field.NewTime(tableName, "source_updated_at")
	_knowledgeEntry.CreatedAt = field.NewTime(tableName, "created_at")
	_knowledgeEntry.UpdatedAt = field.NewTime(tableName, "updated_at")

	_knowledgeEntry.fillFieldMap()

	return _knowledgeEntry
}

type knowledgeEntry struct {
	knowledgeEntryDo knowledgeEntryDo

	ALL             field.Asterisk
	ID              field.Uint64
	SourceKey       field.String // çŸ¥è¯†æ¡ç›®ç¨³å®šé”®ï¼›WPS source_id ä¸ºç©ºæ—¶ç”± keyword è§„èŒƒåŒ–ç”Ÿæˆ
	Keyword         field.String // å…³é”®è¯ï¼›æ—§ WPS å›žå¤è¡¨ç¬¬ä¸€åˆ—
	EntryType       field.String // æ¡ç›®ç±»åž‹ï¼šknowledge/menu_node/chitchat
	Path            field.String // ç”± %ç¼–å· èœå•æ ‘ç”Ÿæˆçš„èœå•è·¯å¾„
	AliasesJSON     field.String // åŒä¹‰é—®æ³• JSON æ•°ç»„
	Category        field.String // åˆ†ç±»
	TagsJSON        field.String // æ ‡ç­¾ JSON æ•°ç»„
	Answer          field.String // æ ‡å‡†å›žç­”ï¼›æ—§ WPS å›žå¤è¡¨ç¬¬äºŒåˆ—
	Content         field.String // /ai æ£€ç´¢ä½¿ç”¨çš„çŸ¥è¯†æ­£æ–‡
	Enabled         field.Bool   // æ˜¯å¦å¯ç”¨
	ExactReply      field.Bool   // æ˜¯å¦å‚ä¸Žæ™®é€šå…³é”®è¯ç²¾ç¡®å›žå¤
	AiEnabled       field.Bool   // æ˜¯å¦å‚ä¸Ž /ai æ£€ç´¢
	LastImportRunID field.Uint64 // æœ€è¿‘ä¸€æ¬¡å¯¼å…¥æ‰¹æ¬¡ ID
	SourceUpdatedAt field.Time   // æºè¡¨äººå·¥ç»´æŠ¤æ—¶é—´
	CreatedAt       field.Time
	UpdatedAt       field.Time

	fieldMap map[string]field.Expr
}

func (k knowledgeEntry) Table(newTableName string) *knowledgeEntry {
	k.knowledgeEntryDo.UseTable(newTableName)
	return k.updateTableName(newTableName)
}

func (k knowledgeEntry) As(alias string) *knowledgeEntry {
	k.knowledgeEntryDo.DO = *(k.knowledgeEntryDo.As(alias).(*gen.DO))
	return k.updateTableName(alias)
}

func (k *knowledgeEntry) updateTableName(table string) *knowledgeEntry {
	k.ALL = field.NewAsterisk(table)
	k.ID = field.NewUint64(table, "id")
	k.SourceKey = field.NewString(table, "source_key")
	k.Keyword = field.NewString(table, "keyword")
	k.EntryType = field.NewString(table, "entry_type")
	k.Path = field.NewString(table, "path")
	k.AliasesJSON = field.NewString(table, "aliases_json")
	k.Category = field.NewString(table, "category")
	k.TagsJSON = field.NewString(table, "tags_json")
	k.Answer = field.NewString(table, "answer")
	k.Content = field.NewString(table, "content")
	k.Enabled = field.NewBool(table, "enabled")
	k.ExactReply = field.NewBool(table, "exact_reply")
	k.AiEnabled = field.NewBool(table, "ai_enabled")
	k.LastImportRunID = field.NewUint64(table, "last_import_run_id")
	k.SourceUpdatedAt = field.NewTime(table, "source_updated_at")
	k.CreatedAt = field.NewTime(table, "created_at")
	k.UpdatedAt = field.NewTime(table, "updated_at")

	k.fillFieldMap()

	return k
}

func (k *knowledgeEntry) WithContext(ctx context.Context) *knowledgeEntryDo {
	return k.knowledgeEntryDo.WithContext(ctx)
}

func (k knowledgeEntry) TableName() string { return k.knowledgeEntryDo.TableName() }

func (k knowledgeEntry) Alias() string { return k.knowledgeEntryDo.Alias() }

func (k knowledgeEntry) Columns(cols ...field.Expr) gen.Columns {
	return k.knowledgeEntryDo.Columns(cols...)
}

func (k *knowledgeEntry) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := k.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (k *knowledgeEntry) fillFieldMap() {
	k.fieldMap = make(map[string]field.Expr, 17)
	k.fieldMap["id"] = k.ID
	k.fieldMap["source_key"] = k.SourceKey
	k.fieldMap["keyword"] = k.Keyword
	k.fieldMap["entry_type"] = k.EntryType
	k.fieldMap["path"] = k.Path
	k.fieldMap["aliases_json"] = k.AliasesJSON
	k.fieldMap["category"] = k.Category
	k.fieldMap["tags_json"] = k.TagsJSON
	k.fieldMap["answer"] = k.Answer
	k.fieldMap["content"] = k.Content
	k.fieldMap["enabled"] = k.Enabled
	k.fieldMap["exact_reply"] = k.ExactReply
	k.fieldMap["ai_enabled"] = k.AiEnabled
	k.fieldMap["last_import_run_id"] = k.LastImportRunID
	k.fieldMap["source_updated_at"] = k.SourceUpdatedAt
	k.fieldMap["created_at"] = k.CreatedAt
	k.fieldMap["updated_at"] = k.UpdatedAt
}

func (k knowledgeEntry) clone(db *gorm.DB) knowledgeEntry {
	k.knowledgeEntryDo.ReplaceConnPool(db.Statement.ConnPool)
	return k
}

func (k knowledgeEntry) replaceDB(db *gorm.DB) knowledgeEntry {
	k.knowledgeEntryDo.ReplaceDB(db)
	return k
}

type knowledgeEntryDo struct{ gen.DO }

func (k knowledgeEntryDo) Debug() *knowledgeEntryDo {
	return k.withDO(k.DO.Debug())
}

func (k knowledgeEntryDo) WithContext(ctx context.Context) *knowledgeEntryDo {
	return k.withDO(k.DO.WithContext(ctx))
}

func (k knowledgeEntryDo) ReadDB() *knowledgeEntryDo {
	return k.Clauses(dbresolver.Read)
}

func (k knowledgeEntryDo) WriteDB() *knowledgeEntryDo {
	return k.Clauses(dbresolver.Write)
}

func (k knowledgeEntryDo) Session(config *gorm.Session) *knowledgeEntryDo {
	return k.withDO(k.DO.Session(config))
}

func (k knowledgeEntryDo) Clauses(conds ...clause.Expression) *knowledgeEntryDo {
	return k.withDO(k.DO.Clauses(conds...))
}

func (k knowledgeEntryDo) Returning(value interface{}, columns ...string) *knowledgeEntryDo {
	return k.withDO(k.DO.Returning(value, columns...))
}

func (k knowledgeEntryDo) Not(conds ...gen.Condition) *knowledgeEntryDo {
	return k.withDO(k.DO.Not(conds...))
}

func (k knowledgeEntryDo) Or(conds ...gen.Condition) *knowledgeEntryDo {
	return k.withDO(k.DO.Or(conds...))
}

func (k knowledgeEntryDo) Select(conds ...field.Expr) *knowledgeEntryDo {
	return k.withDO(k.DO.Select(conds...))
}

func (k knowledgeEntryDo) Where(conds ...gen.Condition) *knowledgeEntryDo {
	return k.withDO(k.DO.Where(conds...))
}

func (k knowledgeEntryDo) Order(conds ...field.Expr) *knowledgeEntryDo {
	return k.withDO(k.DO.Order(conds...))
}

func (k knowledgeEntryDo) Distinct(cols ...field.Expr) *knowledgeEntryDo {
	return k.withDO(k.DO.Distinct(cols...))
}

func (k knowledgeEntryDo) Omit(cols ...field.Expr) *knowledgeEntryDo {
	return k.withDO(k.DO.Omit(cols...))
}

func (k knowledgeEntryDo) Join(table schema.Tabler, on ...field.Expr) *knowledgeEntryDo {
	return k.withDO(k.DO.Join(table, on...))
}

func (k knowledgeEntryDo) LeftJoin(table schema.Tabler, on ...field.Expr) *knowledgeEntryDo {
	return k.withDO(k.DO.LeftJoin(table, on...))
}

func (k knowledgeEntryDo) RightJoin(table schema.Tabler, on ...field.Expr) *knowledgeEntryDo {
	return k.withDO(k.DO.RightJoin(table, on...))
}

func (k knowledgeEntryDo) Group(cols ...field.Expr) *knowledgeEntryDo {
	return k.withDO(k.DO.Group(cols...))
}

func (k knowledgeEntryDo) Having(conds ...gen.Condition) *knowledgeEntryDo {
	return k.withDO(k.DO.Having(conds...))
}

func (k knowledgeEntryDo) Limit(limit int) *knowledgeEntryDo {
	return k.withDO(k.DO.Limit(limit))
}

func (k knowledgeEntryDo) Offset(offset int) *knowledgeEntryDo {
	return k.withDO(k.DO.Offset(offset))
}

func (k knowledgeEntryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *knowledgeEntryDo {
	return k.withDO(k.DO.Scopes(funcs...))
}

func (k knowledgeEntryDo) Unscoped() *knowledgeEntryDo {
	return k.withDO(k.DO.Unscoped())
}

func (k knowledgeEntryDo) Create(values ...*model.KnowledgeEntry) error {
	if len(values) == 0 {
		return nil
	}
	return k.DO.Create(values)
}

func (k knowledgeEntryDo) CreateInBatches(values []*model.KnowledgeEntry, batchSize int) error {
	return k.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (k knowledgeEntryDo) Save(values ...*model.KnowledgeEntry) error {
	if len(values) == 0 {
		return nil
	}
	return k.DO.Save(values)
}

func (k knowledgeEntryDo) First() (*model.KnowledgeEntry, error) {
	if result, err := k.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.KnowledgeEntry), nil
	}
}

func (k knowledgeEntryDo) Take() (*model.KnowledgeEntry, error) {
	if result, err := k.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.KnowledgeEntry), nil
	}
}

func (k knowledgeEntryDo) Last() (*model.KnowledgeEntry, error) {
	if result, err := k.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.KnowledgeEntry), nil
	}
}

func (k knowledgeEntryDo) Find() ([]*model.KnowledgeEntry, error) {
	result, err := k.DO.Find()
	return result.([]*model.KnowledgeEntry), err
}

func (k knowledgeEntryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.KnowledgeEntry, err error) {
	buf := make([]*model.KnowledgeEntry, 0, batchSize)
	err = k.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (k knowledgeEntryDo) FindInBatches(result *[]*model.KnowledgeEntry, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return k.DO.FindInBatches(result, batchSize, fc)
}

func (k knowledgeEntryDo) Attrs(attrs ...field.AssignExpr) *knowledgeEntryDo {
	return k.withDO(k.DO.Attrs(attrs...))
}

func (k knowledgeEntryDo) Assign(attrs ...field.AssignExpr) *knowledgeEntryDo {
	return k.withDO(k.DO.Assign(attrs...))
}

func (k knowledgeEntryDo) Joins(fields ...field.RelationField) *knowledgeEntryDo {
	for _, _f := range fields {
		k = *k.withDO(k.DO.Joins(_f))
	}
	return &k
}

func (k knowledgeEntryDo) Preload(fields ...field.RelationField) *knowledgeEntryDo {
	for _, _f := range fields {
		k = *k.withDO(k.DO.Preload(_f))
	}
	return &k
}

func (k knowledgeEntryDo) FirstOrInit() (*model.KnowledgeEntry, error) {
	if result, err := k.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.KnowledgeEntry), nil
	}
}

func (k knowledgeEntryDo) FirstOrCreate() (*model.KnowledgeEntry, error) {
	if result, err := k.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.KnowledgeEntry), nil
	}
}

func (k knowledgeEntryDo) FindByPage(offset int, limit int) (result []*model.KnowledgeEntry, count int64, err error) {
	result, err = k.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = k.Offset(-1).Limit(-1).Count()
	return
}

func (k knowledgeEntryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = k.Count()
	if err != nil {
		return
	}

	err = k.Offset(offset).Limit(limit).Scan(result)
	return
}

func (k knowledgeEntryDo) Scan(result interface{}) (err error) {
	return k.DO.Scan(result)
}

func (k knowledgeEntryDo) Delete(models ...*model.KnowledgeEntry) (result gen.ResultInfo, err error) {
	return k.DO.Delete(models)
}

func (k *knowledgeEntryDo) withDO(do gen.Dao) *knowledgeEntryDo {
	k.DO = *do.(*gen.DO)
	return k
}
